### ISSUE TITLE
Aptomi core & model cleanup

### ISSUE THREAD

**Issue by romankartgh** [Aptomi/aptomi#301]
- [x] #253 Do not allow to change a cluster via API
- [ ] #270 Introduce namespaces as entities (ACL rules should live inside a NS)
- [x] #282 Validate component instances during policy resolution
- [x] #278 Add a notion of deployment target, remove NS from cluster definition
- [ ] #205 Improve service discovery when contract is implemented via different services
- [x] #302 Agree on the new terminology and rename core entities
- [x] #303 Use label “target” instead of “cluster” to specify placement
- [ ] #307 Remove user from dependency
- [ ] #305 Make service sharing more explicit in policy language
- [ ] #306 kafka.kafka in discovery + input/output parameters for the contract
- [x] #318 Rework how we create/save revisions and desired state
- [x] #321 Better update logic for transferring data from desired state to actual state
- [ ] #335 Support clusters local to namespaces, not only in system namespace
- [x] #327 Figure out EdgesIn & EdgesOut in actual state
